### ISSUE TITLE
Configure uvicorn with a python source file

### ISSUE THREAD

**Issue by raqibhayder** [Kludex/uvicorn#1174]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [x] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Feature request

I want to be able to configure `uvicorn` using a python source file similar to how [gunicorn](https://docs.gunicorn.org/en/stable/settings.html#config-file) does it.  `uvicorn` currently does not support this behaviour. An example `gunicorn_conf.py` file can be found [here](https://github.com/tiangolo/uvicorn-gunicorn-docker/blob/master/docker-images/gunicorn_conf.py)

### Possible usage

Running the command below should start the `uvicorn` server with the given configurations in the `uvicorn_config.py`.

``` sh
uvicorn  example:app -c "uvicorn_config.py"
```

**Comment by akx** [comment]
I'm not sure there needs to be an additional way to configure Uvicorn's CLI, since you can write your own Python program to call `uvicorn.run`... https://github.com/encode/uvicorn/blob/1d9511f0b9dc73867bbbb38f72dbbdcac5478651/uvicorn/main.py#L428

**Comment by Kludex** [comment]
I have the same thoughts as @akx here.

Both gunicorn and celery have this possibility, so we can think about it if this issue gets more ":+1:" .

**Comment by br3ndonland** [comment]
I would be happy to take on a PR if the community is interested enough in this.

I agree with @raqib-hayder. I think support for a configuration file would be helpful, and would bring Uvicorn in line with Gunicorn, Hypercorn (https://github.com/encode/uvicorn/discussions/1105), and other related projects in this respect.

I find myself doing increasing amounts of programmatic configuration for Uvicorn. This configuration sometimes has to be version-aware (i.e., the `reload_excludes` option can only be passed to `uvicorn>=0.15`). It would be helpful for **separation of concerns** to move the configuration into a dedicated file.

A config file would also make it easier to **maintain configurability when layers of abstraction are built on top of Uvicorn**. For example, users might want to start with a pre-configured server like [this](https://inboard.bws.bio), using it as the basis for their project. The base project provides default configuration, but the downstream project might need to change some settings. How should these downstream projects update the Uvicorn configuration if the actual `uvicorn`/`uvicorn.run()` command is in the base project? Environment variables can be used, but then the base project needs to read an environment variable for every Uvicorn config setting, and there are a lot of config settings. With configuration file support, downstream users could simply specify a single environment variable like `UVICORN_CONF` with the path to their configuration file, rather than passing in individual environment variables for every setting they want to configure.

**Comment by misimpso** [comment]
Configuration should be built to work with the `setup.cfg` spec for configuring third-party tools: e.g. [flake8](https://flake8.pycqa.org/en/latest/user/configuration.html).

**Comment by Niccolum** [comment]
> Configuration should be built to work with the `setup.cfg` spec for configuring third-party tools: e.g. [flake8](https://flake8.pycqa.org/en/latest/user/configuration.html).

At first, It could be just file like uvicorn.ini/.yaml/.json/.py. And after that we can support setup.cfg/pyproject.toml and other. (After all it can solve crutch with default parameters with UvicornWorker with gunicorn, for example :)

@Kludex what do you think about this at all after all @br3ndonland thoughts? If you don't have enough time I can create PoC of this, if you don't mind. I think it shouldn't be so hard. I just don't want to waste time on something that will not be included in the final package later.

If don't mind, please tell me, which type of config would you like to see first?

**Comment by florimondmanca** [comment]
Stumbing upon this issue, note that this was discussed in the past, see #322.

**Comment by Kludex** [comment]
In case we want this, we can do something like this: https://stackoverflow.com/a/46391887/13087720

**Comment by lovelydinosaur** [comment]
I'd really like to see Uvicorn on a feature-pause at the moment.

My maintainer-hat is that *right now* we should be closing off any feature suggestions, and just allow `uvicorn` to bed in, while focusing on getting the issue list nicely under control, and making sure that we're in a good, sustainable workflow.

**Comment by Niccolum** [comment]
> Stumbing upon this issue, note that this was discussed in the past, see #322.

To be honest, It's ok for me, while uvicorn is not a prod-ready solution (because of running as gunicorn worker).  But this feature nice to have for the reasons described above
