### ISSUE TITLE
Feature request: Ability to import uvicorn in django to enable websocket support

### ISSUE THREAD

**Issue by caleb15** [Kludex/uvicorn#1297]
### Checklist

- [X] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

When we do `python manage.py runserver` we have a line in our manage.py file `import daphne.server` which enables websocket support with runserver. If we could do the same thing with uvicorn that would let us get rid of daphne entirely. 

### Describe the solution you would like.

websocket support for django runserver

### Describe alternatives you considered

* continue using daphne for runserver (downside: extra dependency)
* use uvicorn with autoreload feature. (downside: devs prefer using runserver)

**Comment by Kludex** [comment]
What needs to be done for that?

**Comment by Kludex** [comment]
Closing as stale.

I'm willing to reopen the issue if more information is provided.

**Comment by Archmonger** [comment]
@Kludex Was looking for a relevant issue when I found this.

If you take a look at the [Django Channels installation docs](https://channels.readthedocs.io/en/stable/installation.html) it recommends installing `daphne` within `INSTALLED_APPS`.

This is in order to override Django Core's built-in `manage.py runserver` command which uses a WSGI server. When installing `daphne`, it gets replaced with an ASGI variant.

I believe this issue is asking for `uvicorn` to be installable as a Django app and to include some code in this repo to override the `runserver` command.

[Take a look how Daphne overrides the `runserver` command](https://github.com/django/daphne/tree/main/daphne/management/commands).

**Comment by Kludex** [comment]
Can that code live outside uvicorn, and we just add to the documentation?

**Comment by Archmonger** [comment]
Yep, from a technical perspective nothing is stopping it from being external, might be a bit awkward though.

I could imagine a separate `uvicorn_django` package, which can be installed via the `extras_require` `uvicorn[django_compatible]`.

Then one of two paths could be taken:
- Tell the user to add `uvicorn_django` to `INSTALLED_APPS`
- Tell the user to add `uvicorn` to `INSTALLED_APPS`
   - It would be possible to create some infrastructure in `uvicorn/__init__.py` to push the `management` commands from `uvicorn_django` directly into `uvicorn.management` (when available).
   - To oversimplify what would be put in `uvicorn/__init__.py`: `management = importlib("uviccorn_django").management`

**Comment by Kludex** [comment]
A third party package can important uvicorn, and do what you say as well... 😅

I think this is out of scope for uvicorn.
