### ISSUE TITLE
dotenv file not loaded correctly

### ISSUE THREAD

**Issue by movabo** [Kludex/uvicorn#1319]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

Uvicorn does not load the dot env file as expected when running it via over the command line or via `uvicorn.run`.

### Steps to reproduce the bug

File `bug.py`:
```py
import uvicorn


if __name__ == '__main__':
    uvicorn.run('bug:app', host='localhost', env_file='.env')

# Uvicorn's example app:
async def app(scope, receive, send):
    assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```
File `.env`:
```
UVICORN_PORT=8081
PORT=8081
```
Shell:
```sh
$ uvicorn bug:app --env-file .env
or
$ python bug.py
```
Output (both times):
```
/venv/bin/python3.10 /bug.py
INFO:     Loading environment from '.env'
INFO:     Started server process [11355]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```

### Expected behavior

Server running on port 8081.

### Actual behavior

Server running on port 8000:
```
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```

### Environment

 - `uvicorn --version`
   - `Running uvicorn 0.16.0 with CPython 3.10.0 on Linux`
 - Run commands:
   - `uvicorn bug:app --env-file .env`
   - `python bug.py`

**Comment by Kludex** [comment]
I see what you mean, but I don't think it was created with the intention to be used by uvicorn itself :thinking: 

As the load happens after the configurations are in place... See more: https://github.com/encode/uvicorn/pull/470

It can be a valid issue tho

**Comment by movabo** [comment]
Okay, I thought it would go hand in hand with the environment variables mentioned on the [settings docs page](https://www.uvicorn.org/settings/):

> You can also configure Uvicorn using environment variables with the prefix `UVICORN_`. For example, in case you want to run the app on port `5000`, just set the environment variable `UVICORN_PORT` to `5000`.

~~However, this doesn't seem to work as well (at least with the fish shell):~~
```
$ set UVICORN_PORT 8081
$ python bug.py
```
~~produces still the same output with port 8000.~~

Edit: I made a mistake when setting the environment variable, it's `set -x UVICORN_PORT 8081` and then it works.

**Comment by Niccolum** [comment]
@movabo I'm not contrubutor, but saw source code and don't know why it's happens. Can you say your click version and can you debug this method in click
https://github.com/pallets/click/blob/main/src/click/core.py#L1360

Is it exists ctx.context_settings == {"auto_envvar_prefix": "UVICORN"} ?

Because uvicorn use it's click feature here:
https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L53

Just looks like click issue

**Comment by movabo** [comment]
@Niccolum, when running `python bug.py`, the method is not called.
When running `uvicorn bug:app --env-file .env`, ctx does not have the attribute `context_settings` (`AttributeError: 'Context' object has no attribute 'context_settings'`), but it has directly the attribute `auto_envvar_prefix`. And here, it is 'UVICORN' (i.e. `ctx.auto_envvar_prefix == 'UVICORN'` yields `True`).

**Comment by Niccolum** [comment]
@movabo E.g. in cli directly UVICORN_PORT worked, but not worked with `uvicorn.run`? Or despite of it the port still does not change in both cases? As I see in your issue - not working both cases?

UPD: please, tell us your click version
UPD2: I see why if you run python bug.py - cli func not running. Quick fix - use `uvicorn.main(auto_envvar_prefix='UVICORN', ...)` instead of `uvicorn.run(...)`.
Note: I don't check it locally, but, according click and uvicorn source codes - it must work (method will be called)

**Comment by movabo** [comment]
No, it did not work in any case. Neither `python bug.py`, nor `uvicorn bug:app --env-file .env`~~, nor `set UVICORN_PORT 8081 & python bug.py`~~.

The click version is 8.0.3.

[Edit](https://github.com/encode/uvicorn/issues/1319#issuecomment-1010294812)

**Comment by movabo** [comment]
`auto_envvar_prefix` is an unexpected keyword argument for uvicorns config, so it does not work. Also, as I already mentioned, the value of `auto_envvar_prefix` is already `UVICORN` so I don't see what it should change.

**Comment by Niccolum** [comment]
> `auto_envvar_prefix` is an unexpected keyword argument for uvicorns config, so it does not work. Also, as I already mentioned before, it the value of `auto_envvar_prefix` is already `UVICORN` so I don't see what it should change.

If I understand source code correctly - if you run `uvicorn.run` - auto_envvar_prefix do not use. But if you use uvicorn.main(auto_envvar_prefix='UVICORN', ...) or just `uvicorn.main(...)` instead - it must pass auto_envvar_prefix to click. After all I'll try to understand why it happens and if I found solution - I return here asap.

**Comment by movabo** [comment]
Ah, I overlooked mains decorators, however the keyword-argument for `main` also does not change anything.

**Comment by Niccolum** [comment]
@movabo Quick update
Yes, it's bug. Two bugs

Click search env vars when running uvicorn.main (and only main)

But load envs do after that (after searching in environment), in func, which run after in config init

https://github.com/encode/uvicorn/blob/master/uvicorn/main.py#L443

https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L347


So:
1. Change docs to use run instead of main in .py files
OR
Run main inside run for collect data.
OR
Something else that fix it

2. Add decorator to run to load envs before running cli 
OR 
Create custom func to load inside callback argument to option (not sure if it runs before)

@Kludex what do you think about this thread and this message at all?

**Comment by movabo** [comment]
@Niccolum, I did not correctly set the environment variable in my shell, so directly setting the environment variable in the shell works.

**Comment by Niccolum** [comment]
> @Niccolum, I did not correctly set the environment variable in my shell, so directly setting the environment variable in the shell works.

If you set env before running - it woll works well. But it won't work properly with env file in both case.

**Comment by Niccolum** [comment]
I came up with solution with small changes.  I'll implement it this week, if not someone implement it faster :)

**Comment by Kludex** [comment]
> @Kludex what do you think about this thread and this message at all?

I don't think this is a bug. This works as intended, even if it doesn't work with the `UVICORN_` environment variables.

I guess the question now is if we want to change the behavior of `env_file` so `uvicorn` can load the environment variables with prefix `UVICORN_` located on that file... And I'm not sure if it's worth it.
