### ISSUE TITLE
Finesse signals

### ISSUE THREAD

**Issue by lovelydinosaur** [Kludex/uvicorn#158]
We currently only implement graceful shutdown.

We should provide for force-quit as well. (Perhaps Ctrl+C during the graceful shutdown could invoke a force quit?)

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/158">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/158/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/158/pledge.svg">
</picture>
</a>

**Comment by blueyed** [comment]
Also currently SIGINT (KeyboardInterrupt) is just swallowed when there is a blocking request.

This is a problem with `loop.add_signal_handler`, which then handles them only when processing events, i.e. KeyboardInterrupt is raised with a blocking read, but only handled then when processing events (related code: https://github.com/python/cpython/blob/a6fce19968cd39dfbc2684f97ca3184d9996f61e/Lib/asyncio/unix_events.py#L100-L103).

I am not sure that `add_signal_handler` is required really, since it only allows to interact with the event loop, which is not being done in uvicorn, is it?

I think it would be better to use `signal.signal` directly, and even raise KeyboardInterrupt from there then if `force_exit` is True already, etc.


Something along:

```diff
stash@{0}: WIP on master: 01e1858 Changed reload check time to 1 sec from 100ms (#341)
---
 uvicorn/main.py | 32 +++++++++++++++-----------------
 1 file changed, 15 insertions(+), 17 deletions(-)

diff --git a/uvicorn/main.py b/uvicorn/main.py
index cbc578c..cb4be1b 100644
--- a/uvicorn/main.py
+++ b/uvicorn/main.py
@@ -382,12 +382,13 @@ def run(self, sockets=None, shutdown_servers=True):
 
     async def main_loop(self):
         counter = 0
-        should_exit = await self.on_tick(counter)
-        while not should_exit:
-            counter += 1
-            counter = counter % 864000
-            await asyncio.sleep(0.1)
+        while True:
             should_exit = await self.on_tick(counter)
+            if should_exit:
+                break
+            counter += 1
+            counter = counter % 86400
+            await asyncio.sleep(1)
 
     async def on_tick(self, counter) -> bool:
         # Update the default headers, once per second.
@@ -440,22 +441,19 @@ def run(self, sockets=None, shutdown_servers=True):
                 await asyncio.sleep(0.1)
 
         # Send the lifespan shutdown event, and wait for application shutdown.
-        if not self.force_exit:
-            await self.lifespan.shutdown()
+        # Await it to avoid warning about destroyed finished task?!
+        await self.lifespan.shutdown()
 
     def install_signal_handlers(self):
-        loop = asyncio.get_event_loop()
-
-        try:
-            for sig in HANDLED_SIGNALS:
-                loop.add_signal_handler(sig, self.handle_exit, sig, None)
-        except NotImplementedError as exc:
-            # Windows
-            for sig in HANDLED_SIGNALS:
-                signal.signal(sig, self.handle_exit)
+        for sig in HANDLED_SIGNALS:
+            signal.signal(sig, self.handle_exit)
 
     def handle_exit(self, sig, frame):
-        if self.should_exit:
+        print("handle_exit", sig)
+        if self.force_exit:
+            if sig == signal.SIGINT:
+                raise KeyboardInterrupt
+        elif self.should_exit:
             self.force_exit = True
         else:
             self.should_exit = True
```

```
INFO: Shutting down
INFO: Waiting for connections to close. (CTRL+C to force quit)
^Chandle_exit 2
INFO: Finished server process [15943]
^Chandle_exit 2
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/daniel/Vcs/uvicorn/uvicorn/main.py", line 454, in handle_exit
    raise KeyboardInterrupt
KeyboardInterrupt
ERROR: Task was destroyed but it is pending!
task: <Task pending coro=<LifespanOn.main() running at /home/daniel/Vcs/uvicorn/uvicorn/lifespan/on.py:44> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6fc51bd5b8>()]>>
INFO: ASGI 'lifespan' protocol appears unsupported.
```

Related code in hyperloop: https://gitlab.com/pgjones/hypercorn/blob/4901eedeeb9673cfcc13068beaf479ba57a8b93a/hypercorn/asyncio/run.py#L128-143 - handles it a bit better, e.g. with regard to Python waiting on running threads.

My first attempt was to uninstall/remove the signal handler on shutdown, which helps with threads that are being waited for, but it then looked like just using `signal.signal` might be better.

**Comment by lovelydinosaur** [comment]
> is just swallowed when there is a blocking request.

What do you mean exactly "when there is a blocking request"?
Do you mean if the event loop has been blocked (eg. a raw `time.sleep(...)` instead of the async variant?)

Perfectly happy to consider any PRs swtiching around our signal handling if it's clear how they ought to look.

**Comment by lovelydinosaur** [comment]
Closing this ticket, as we now *have* a force quit on shutdown.
