### ISSUE TITLE
Unclear documentation about limit_concurrency and backlog settings

### ISSUE THREAD

**Issue by siminchengithub** [Kludex/uvicorn#1811]
According to the doc, **limit_concurrency** is the maximum number of concurrent connections and any extra connection requests will get 503; **backlog** is the maximum number of connections in the backlog waiting to be handled. 
My confusion about them:

1. when **limit_concurrency** is reached, do all extra requests get 503 straight without being put in the backlog first?
2. when there are requests in the backlog and **limit_concurrency** is reached, will those pending requests get 503 one by one?  Gunicorn would just process them whenever possible, but the definition of **limit_concurrency** in Uvicorn seems to imply otherwise.
3. when backlog is full while **limit_concurrency** is not yet reached, what status code do the extra requests get?
4. when backlog is full and **limit_concurrency** is also reached, what status code do the extra requests get?

If someone can also describe more clearly how Uvicorn interacts with a socket and its backlog in relation to its limit_concurrency setting would be great!

**Comment by Kludex** [comment]
PR is always welcome to improve documentation...

**Comment by siminchengithub** [comment]
@Kludex  those are my questions though, once I understand the answers I'm happy to improve the documentation

**Comment by chaselambda** [comment]
I'm trying to figure out what the backlog parameter does as well. It looks like it ultimately goes to the `listen` syscall.

The original PR doesn't seem to clarify what's going on: https://github.com/encode/uvicorn/pull/545/files

In playing around on Ubuntu 20.04:
- It does seem like backlog is indeed getting sent to the `listen` syscall:
![image](https://user-images.githubusercontent.com/442311/208808717-a6d62ddc-8657-402e-9991-55821e6d7ad6.png)
- All my requests seem to get queued up with `curl`.. nothing gets prematurely dropped with a backlog of 1
- `ss -a` indeed shows Send-Q is updated (though I don't know precisely what this means):
![image](https://user-images.githubusercontent.com/442311/208809696-a1e14933-7fab-4a7e-ad4d-6d8f9f75cda6.png)

I think ultimately, the `backlog` parameter doesn't actually drop TCP connections, because TCP will retry. Here are two sources that suggest this:

1)
![image](https://user-images.githubusercontent.com/442311/208807436-0bce2224-90d7-421e-8ea8-1617762fd6dc.png)

2)
![image](https://user-images.githubusercontent.com/442311/208809592-f493515b-572c-4e2e-9a2c-cf8182c0e47d.png)

Given this, I don't have a good idea when anyone would ever use `backlog`. Maybe some TCP connections are really picky about getting SYN responses quickly, and will otherwise time out faster? Something detailed like that.

**Comment by chaselambda** [comment]
`limit_concurrency` docs seem to be off-by-one. `limit_concurrency` of 1 will drop _all_ requests. And a value of 2 will allow at most 1 request. That's because this `>=` sign should probably be simply `>`.
![image](https://user-images.githubusercontent.com/442311/208810524-5c377c98-ab12-4798-8af1-29b58a1a03fe.png)

That structure is added to before the check is made:
![image](https://user-images.githubusercontent.com/442311/208810603-51542265-d3c1-43b4-b53d-15a9a341e23a.png)

**Comment by chaselambda** [comment]
To answer this rephrased question: "when limit_concurrency is reached, do all extra requests get 503 immediately"

Answer: No. You first have to wait for one of the workers to finish its last request, it will then drop all requests. Per worker. That's because each worker is running on a single thread, so it can't go and tell some incoming request to drop. You would *hope* that there would be some OS-layer tool that would do that dropping for you (like `backlog`), but it seems like that's not the case. `limit_concurrency` is simply written in python, so that can't be run while there's a blocking request happening.

**Comment by euri10** [comment]
been a while but iirc there's 0 link between the `limit_concurrency` and the `backlog` flags,  https://stackoverflow.com/a/72897345/3581357

**Comment by chaselambda** [comment]
@euri10 I'm curious what part of that answer is additionally helpful here?

That answer states "backlog is passed down the loop.create_server and ultimately will determine the number of sockets listening.", which I believe is incorrect. There's only one socket listening, with a `backlog` parameter passed to it, as I've mentioned above.

"limit-concurrency is just here to tell, after x responses issue a 503" I think is not very clear. My description above seems to be more detailed and specific.

Maybe you understand something I do not, but from what I can glean you're just adding that answer in case it's helpful, not because you have confidence it's helpful. Which is a fine thing, I just wanted to check.

**Comment by euri10** [comment]
I didnt read your answer, I was answering OP ;)

**Comment by siminchengithub** [comment]
@euri10 that stackoverflow link simply states there is no link with a wrong definition of limit_concurrency and no explanation to the dynamic between limit_concurrency and backlog. If you are confident that there is no link, then please explain more exactly why there is no relationship by elaborating the answers to my questions.
