### ISSUE TITLE
Test Gunicorn Worker

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1834]
The idea here is to create a setup to test the `gunicorn` worker classes that we have.

I don't know how is the best way to achieve this, as [`gunicorn` test suite](https://github.com/benoitc/gunicorn/tree/master/tests) didn't give me much insight on how we can test this integration without `unittest.mock`. Suggestions are welcome.

If you are interested on working on this, go ahead. Some clarifications:

1. Avoid integration kind of setup. I want to keep it simple.
2. Avoid `unittest.mock` - if inevitable, explain the reason.
3. Add test coverage up to 100% on the `workers.py`. 

## Notes

When doing this, please change those lines: https://github.com/encode/uvicorn/blob/eec7d22ecc0c8926feb365ac7708918e32725f4f/setup.cfg#L39-L43

To something more like: https://github.com/encode/starlette/blob/048643adc21e75b668567fc6bcdd3650b89044ea/setup.cfg#L41-L42

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/1834">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/1834/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/1834/pledge.svg">
</picture>
</a>

**Comment by br3ndonland** [comment]
I can take this on. I agree we should keep it simple and focus on unit testing.

[One way I've approached unit testing without mocks](https://github.com/br3ndonland/inboard/blob/7fbde3ee38d8d1270191619008fd58d1bc4b2132/tests/test_gunicorn_conf.py#L83-L111) is by starting a Gunicorn server with the `--print-config` option. This does actually start the Gunicorn server, but Gunicorn will just print out the config and then shut down. You can then parse the output and assert that Gunicorn is using the appropriate settings.

I'll think about some other complementary ways to approach testing of the worker.

**Comment by br3ndonland** [comment]
Just dropping a note here to say that I'm working on this and making some slow progress.

I started off with the `--print-config` strategy I mentioned in https://github.com/encode/uvicorn/issues/1834#issuecomment-1372902834, but it wasn't very useful. We're not doing much modification of the Gunicorn config here, other than just setting the worker class, and I've also found that this strategy doesn't really test functionality of the server at all. For example, I can run a command like `gunicorn --print-config --worker-class "this.worker.DoesNotExist" "example_package.example_module:app"`, and Gunicorn will start up, print out the config stating that the worker class is `this.worker.DoesNotExist`, and exit successfully, even though that config would clearly not work.

Instead, I'm working on some testing capabilities that will:

- Provide a running (not mocked), context-managed Gunicorn server with a client for testing requests and responses. This will probably just be an `httpx.Client` instance, almost like a minimal version of the Starlette `TestClient`.
- Provide a means of programmatically hooking into the Gunicorn process manager (the "arbiter"). This would be helpful for testing signal handling, and we have had a number of issues and PRs that relate to signal handling (such as encode/uvicorn#1116, encode/uvicorn#1579 and encode/uvicorn#1710). It seems like we need some means of testing how signals are handled by both the Uvicorn worker and the Gunicorn arbiter. In the future, developers working on PRs like encode/uvicorn#1710 should have a simple way of testing changes to the workers.

Hope to have a PR for review soon.

**Comment by jawang94** [comment]
+1

**Comment by br3ndonland** [comment]
I'm working through a few tedious limitations right now. One of them relates to conditional test coverage.

As correctly suggested in the description, we need to change our coverage.py config from `include = uvicorn/*, tests/*` to `source_pkgs = uvicorn, tests`. This is because the current `include` syntax actually _excludes_ `uvicorn.workers` from test coverage. Switching to `source_pkgs` will include all the modules.

The limitation is that we can't cover `uvicorn.workers` or the associated tests on Windows. [Gunicorn doesn't test on Windows at all](https://github.com/benoitc/gunicorn/blob/792edf6d9aabcbfb84e76be1d722ac49c32dc027/.github/workflows/tox.yml#L12) because it depends on various Unix utilities like `fcntl`.

How do we tell coverage.py, "please exclude `uvicorn.workers` and `tests.test_workers` from coverage on Windows"? Seems like there should be some obvious way to do this, but I'm not sure.

[Coverage.py has an `--omit` flag](https://coverage.readthedocs.io/en/latest/source.html), but I don't think this flag can handle platform-specific conditionals like we need here.

I tried setting pragmas at the top-level of the modules, but coverage-conditional-plugin doesn't support this (wemake-services/coverage-conditional-plugin#2).

Am I missing something? Or will I need to do a PR that resolves wemake-services/coverage-conditional-plugin#2 in order to unblock this?

I guess the simplest option would be to add a `# pragma: py-win32` comment to every statement that's not covered. It would add a lot of comments.

**Comment by br3ndonland** [comment]
> Am I missing something? Or will I need to do a PR that resolves wemake-services/coverage-conditional-plugin#2 in order to unblock this?

PR submitted (wemake-services/coverage-conditional-plugin#221). This feature will enable entire modules to be conditionally omitted from test coverage measurement.

**Comment by br3ndonland** [comment]
Coding for this is done, and we now have a nice way to omit the worker code from test coverage measurement on Windows, thanks to [coverage-conditional-plugin 0.9.0](https://github.com/wemake-services/coverage-conditional-plugin/releases/tag/0.9.0).

PR coming up shortly.

**Comment by Kludex** [comment]
Thanks 🙏

**Comment by Kludex** [comment]
- The workers are moved to the [Uvicorn Worker](https://github.com/Kludex/uvicorn-worker) package.

I'll deprecate the workers within Uvicorn.
