### ISSUE TITLE
Add Python 3.12 to the pipeline

### ISSUE THREAD

**Issue by Kludex** [Kludex/uvicorn#1847]
What is needed here:

- [ ] Add an entry to the matrix of Python versions on `.github/workflows`.
- [ ] Fix the pipeline - it will fail on a flake8 dependency.

**Comment by TobeTek** [comment]
Hello 👋

I'd like to work on this.

Did a bit of groundwork as well.
I've only been able to find **alpha** versions of Python 3.12 on GitHub at the moment. So that's what will be used for the matrix?

The `flake8` error seems to be coming from `importlib_metadata`. Precisely
```
AttributeError: 'EntryPoints' object has no attribute 'get'
```

I don't have any solutions yet, but still doing more research.

**Comment by Kludex** [comment]
Hey! :wave: 

Thanks for the interest! You can use `3.12-dev` on the matrix.

> The flake8 error seems to be coming from importlib_metadata. Precisely

Yeah, I think we need to bump `flake8`, or add a marker on the requirement for `importlib_metadata` - a marker already exists, as we see below, but maybe we need to tweak it a bit to see what works:

https://github.com/encode/uvicorn/blob/2351d5ff2b068d7bcba6eaccde83bc90b0727c89/requirements.txt#L18

**Comment by TobeTek** [comment]
Hello again! 
Thanks for responding. Finally found time over the weekend to work on this.

Finally resolved the dependency conflicts. `flake8==3.9.2` doesn't pin a version for `importlib_metadata`, so other packages suggested newer versions and pip had no way of telling the incompatibility. I thought of playing around with the version of `importlib_metadata` but I finally decided to instead bump up the `flake8` version to `>=4.0`, as well as dropping `mkdocs` to a lower minor version. Could there be unexpected consequences to this?

[requirements.txt](https://github.com/TobeTek/uvicorn/blob/b5c8e3b93f399ac2c712111241ab5ed0d1e7690c/requirements.txt#L17)
```
flake8>=4.0.0
# importlib-metadata==4.13.0; python_version>='3.7'
...
# Documentation
mkdocs>=1.2.4
mkdocs-material>=8.2.7
```

Now a new problem, the lint and build/docs scripts run fine on the linux/ubuntu environments, but since `uvloop` doesn't yet have a wheel on **PyPI** for Python 3.12, pip install fails on macOS and windows. Possible ideas?

The actual **"Run tests"** seem to be failing however. Here's a link to the [most recent workflow run](https://github.com/TobeTek/uvicorn/actions/runs/3980547991/jobs/6823720061)

**Comment by Kludex** [comment]
> Now a new problem, the lint and build/docs scripts run fine on the linux/ubuntu environments, but since uvloop doesn't yet have a wheel on PyPI for Python 3.12, pip install fails on macOS and windows. Possible ideas?

Ah... Then we need to wait...

**Comment by Kludex** [comment]
I'm going to close this just for housekeeping. We need to wait for uvloop anyway.
