### ISSUE TITLE
Log errors with exception info

### ISSUE THREAD

**Issue by AzMoo** [Kludex/uvicorn#198]
When logging errors it would be great if the exception info was passed as well. When logging to sentry we're getting messages such as "ASGI callable returned without completing response." with no context as to what's actually generating the message. 

For example: https://github.com/encode/uvicorn/blob/919af04b65c72140fa1ffbd8945d375c9de06188/uvicorn/protocols/http/httptools_impl.py#L405

So I've just realised this isn't actually raising an exception at all, it's just logging an error. Still, including a traceback would be incredibly beneficial.

**Comment by lovelydinosaur** [comment]
I'd happily take a pull request adding tracebacks to the set of 3 error conditions in `run_asgi`. (They'd need to be added for both the `httptools` and `h11` implementations.)

That' not going to help you any further in this particular case, since you've already tracked down the error message to the code in uvicorn that logs it. The issue you'll need to look into is why you have a view that is starting the response but then returning normally, with no exception, having failed to complete the response.

**Comment by matteosimone** [comment]
The actual errors might be related to #201.  I would try to upgrade to 0.3.8 and see if it resolves this. This of course won't resolve your actual issue of wanting tracebacks though.

**Comment by almarklein** [comment]
@matteosimone Maybe you can make use of `sys.exc_info()`?

**Comment by lovelydinosaur** [comment]
Resolved in 0.3.19
