### ISSUE TITLE
Add ping-interval and ping-timeout options

### ISSUE THREAD

**Issue by dakra** [Kludex/uvicorn#245]
daphne has these options to send regularly a `ping` to the client to see if it's still connected.

The [asgi documentation](https://asgi.readthedocs.io/en/latest/specs/www.html#websocket) also says:

``` text
WebSocket protocol servers should handle PING/PONG messages themselves, 
and send PING messages as necessary to ensure the connection is alive.
```

**Comment by lovelydinosaur** [comment]
Yup, I'd be in favor of that.

**Comment by Andrew-Chen-Wang** [comment]
Any updates or other PRs on this yet? I think I can do it... if I get time off school and ap tests. It seems like the websocket library at aaugustin/websockets#449 has this automatically set up. I don't know about WSProto; however, the original ping/pong frame for websockets had this implementation inside of its documentation that can be translated to WSProto: https://github.com/aaugustin/websockets/pull/449/files

I'm not exactly sure how WSProto works though... is that entire library synchronous? @tomchristie Because if so, would the Server class object need to have some internal newly threaded runner?

Also, testing? Is this testing phase for this auto ping/pong going to be implemented here?

**Comment by ghost** [comment]
What's more, websockets have ping_intrval and ping_timeout parameter, which used to specify ping/pong circle interval. However, it seems uvicorn can only adapt the default values(which are 20s both) and there is not way to specify them.
