### ISSUE TITLE
Logging user session

### ISSUE THREAD

**Issue by jon-torodash** [Kludex/uvicorn#293]
Feature request: it would be nice to have as an option the ability to log specific headers (I'm thinking particularly of session_id, but any configurable) if they exist in `uvicorn.protocols.http.httptools_impl.RequestResponseCycle#send`. Is that something which the maintainers would add if I implement and open a PR for it? It can be helpful to identify certain requests at a low level that might be filtered out by higher layers before other identifying information would be available.

**Comment by lovelydinosaur** [comment]
Bit hard to say. I guess we *could* accept pull requests that make the access logging more configurable, but I'm not too sure how they'd look.

For logging user sessions you *might* think about preferring application-level middleware, once you've got access to the username etc, and can log something more comprehensive.

I'm going to close this issue off, since it's a bit open-ended, but we *could* consider specific pull requests related to this.
