### ISSUE TITLE
How to add uvicorn options when running with gunicorn?

### ISSUE THREAD

**Issue by nhumrich** [Kludex/uvicorn#343]
The deployment section of uvicorn recommends using gunicorn for production scenarios. I want to change the server header as well as set the proxy_headers for uvicorn. In python I can do this with:
```python
uvicorn.run(app, host='0.0.0.0', port=8445, headers=[('Server', 'MyCustom')], proxy_headers=True)
```

How do I set those when using gunicorn? I guess a more generic question for the masses is how do I pass config's through to uvicorn?

**Comment by lovelydinosaur** [comment]
We don't currently have a *documented* way of doing that, but if you take a look at the worker class you'll see that you can subclass it and override `CONFIG_KWARGS`.

https://github.com/encode/uvicorn/blob/master/uvicorn/workers.py

> I guess a more generic question for the masses is how do I pass config's through to uvicorn?

I don't think there's going to be any good way of dealing with this, since if we're using gunicorn, then we're limited to gunicorn's config options.

(Tho eg. if gunicorn already supports custom headers, then we could support getting those from whatever is in it's config?)

**Comment by nhumrich** [comment]
Sounds good. Thanks.
