### ISSUE TITLE
Any reason why uvloop is pinned to 0.12 in setup.py but not requirements.txt?

### ISSUE THREAD

**Issue by Lawouach** [Kludex/uvicorn#414]
Hi there,

I was wondering if there was a strict reason for pinning uvloop?

Cheers,

**Comment by lovelydinosaur** [comment]
Generally we should pin pre 1.0 releases to the median version (eg 0.3.x) and post 1.0 releases to the major version (eg 3.x)

We do this because we don’t know if there may be breaking API changes on updates.

Actually tho, in the case of uvloop, we might be okay with just pinning to 0.x since there isn’t really much API that’s likely to change between releases, so I’d be okay with us adopting a more relaxed pinning in that particular case.

**Comment by Lawouach** [comment]
I can fully appreciate the thinking here. It makes a lot of sense. I'm happy either way, just wanted to understand the difference between the two files.

**Comment by lovelydinosaur** [comment]
Now resolved, via #406. Next release will be pinned at `uvloop==0.*`

**Comment by Lawouach** [comment]
Much appreciated!
