### ISSUE TITLE
CLI uvicorn main:app ModuleNotFound, but right click file name in Pycharm runs ok?

### ISSUE THREAD

**Issue by scheung38** [Kludex/uvicorn#437]
This is my file structure:

proj_root
/rest_api/main.py

$ cd rest_api

$ uvicorn rest_api:APP --reload

results in one of the files that are referenced locally from within my project fails to import:

ModuleNotFoundError: No module named xxxx

But when Right-Click rest_api.py in Pycharm it runs ok:

INFO: Started server process [14928]
INFO: Waiting for application startup.
INFO: Uvicorn running on http://0.0.0.0:5000 (Press CTRL-C to quit)

**Comment by lovelydinosaur** [comment]
It looks like the issue is that you're running `uvicorn rest_api:APP` but you're *already* in the `rest_api` directory.

I'm not sure what extra work we could be doing to guide folks getting an import error due to incorrect import paths? Any thoughts from anyone here? Does Gunicorn have more useful messaging in any respect here?
