### ISSUE TITLE
How to run app from app factory?

### ISSUE THREAD

**Issue by heckad** [Kludex/uvicorn#492]
I try to run the server by command `uvicorn my_packege.app:create_app` and got error: `TypeError: __call__() missing 1 required positional argument: 'send'`. What could be the reason?

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/492">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/492/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/492/pledge.svg">
</picture>
</a>

**Comment by yonromai** [comment]
ping?

**Comment by lovelydinosaur** [comment]
We don't document an app factory style anywhere, and it's not supported.
Run an app *instance* instead.

**mypackage.py**

```python
app = create_app()
```

**Then...**

```shell
$ uvicorn my_package:app
```

I'm curious where the intent is coming from here, since Gunicorn doesn't use an "app factory" style either. Is there a particular Python framework / server that you're comparing this too?

(I'm not totally against us having an invocation like that, but it's not expected usage, and it's not obvious that it's required)

**Comment by heckad** [comment]
> I'm curious where the intent is coming from here, since Gunicorn doesn't use an "app factory" style either. Is there a particular Python framework / server that you're comparing this too?

flask, aiohttp

> (I'm not totally against us having an invocation like that, but it's not expected usage, and it's not obvious that it's required)

Factory need when you need test the app. If you use a global app then you get one app but in unit tests need to create an app for each test.

**Comment by lovelydinosaur** [comment]
Okay, reviewed https://flask.palletsprojects.com/en/1.1.x/tutorial/factory/ and I see where you're coming from.

I'm used to using a twelve-factor style, and making sure that the system environment variables are setup differently for testing.

We could possibly accept an `--app-factory` flag, which changes the main callable from "the app itself" into "a function returning the app".

Alternately you could instantiate the default application using the factory, so...

```python
def create_app(...):   # We can use this to create a different app instance for testing.
   ...

app = create_app()  # The default case.
```

**Comment by joaufi** [comment]
Recently ran into this myself; the main reason my team did not want to use `app = create_app()` is that it would instantiate an instance whenever the module it exists in (e.g. `from cool_web_thing.app import app`) is imported (`import cool_web_thing.app`) and we weren't sure we wanted that to happen.

We got around it by creating a separate module `from cool_web_thing._devel import app` which we only use for testing changes locally (in production we use Gunicorn).

Also, fwiw, Gunicorn does allow using an app-factory / function:

```shell
gunicorn cool_web_thing.app:create_app() -b :5000 -k uvicorn.workers.UvicornWorker --reload
```

Works while:

```shell
uvicorn cool_web_thing.app:create_app() --port 5000 --reload
```

Does not.

**Comment by tribals** [comment]
Creating application as global variable in some module is *worst* ever possible option in the world. Mentioned *twelve-factor app* has absolutely nothing to do with such style of programming.

**Comment by florimondmanca** [comment]
I _think_ a lazy loading pattern ought to address your use case here…?

```python
# cool_web_thing.py
from .factory import create_app

class LazyApp:
    def __init__(self):
        self._app = None

    async def __call__(self, scope, receive, send):
        if self._app is None:
            self._app = create_app()
        await self._app(scope, receive, send)

app = LazyApp()
```

Run as 

```bash
uvicorn cool_web_thing:app
```

as usual, except the _actual_ app will be instantiated on the first request — meaning you're not risking an "instantiate on module import".

Going to close this off for now since I'm not sure we're going to support app factories _just yet_, especially since this seems to be motivated in more advanced use cases (when startup time matters, e.g. very-large-scale apps/projects), and in that case a bit of extra code like the above shouldn't be an issue.

**Comment by kristjanvalur** [comment]
application factories were added to flask due to the need to not having application creation a side effect of importing modules.  It also allows having different versions/configurations of applications existing at the same time, which is great for unit tests.  This pattern extends further, in that _settings_ are typically stored as an object on the application itself, rather than statics in a settings module.  Different settings can thus be created for different purposes, without having to restart the entire process.
I am a bit surprised that this kind of pattern isn't encouraged and supported by starlette / uvicorn, since it evolved as a response to a need.

**Comment by laco** [comment]
:arrow_up: I've had some spare time, and I've created a small PR to support this case. I've read the contribution guide, and I feel bad not asking permission to work on this from the maintainers. But at this point the code was already done. :)

**Comment by butla** [comment]
> > I'm curious where the intent is coming from here, since Gunicorn doesn't use an "app factory" style either. Is there a particular Python framework / server that you're comparing this too?
> 
> flask, aiohttp
> 
> > (I'm not totally against us having an invocation like that, but it's not expected usage, and it's not obvious that it's required)
> 
> Factory need when you need test the app. If you use a global app then you get one app but in unit tests need to create an app for each test.

Just FYI, [Gunicorn officially supports this pattern](https://docs.gunicorn.org/en/stable/run.html?highlight=application%20factory#commands). And yeah, it's great for testability.

**Comment by KyleJamesWalker** [comment]
You can also just add the following to the file that contains your factory:

``` python
if __name__ == "__main__":
    app = application()
```

Note: This is the first time using uvicorn, so I haven't fully tested this out, but it's at least loading and running just fine.

**Comment by Pierre-Alexandre35** [comment]
any updates?

**Comment by Kludex** [comment]
This was merged years ago: https://www.uvicorn.org/#application-factories
