### ISSUE TITLE
Add argument for changing logger instance 

### ISSUE THREAD

**Issue by rsaleev** [Kludex/uvicorn#493]
I think it's possible to make it easier to run uvicorn programmatically with custom logger.
I'm using my custom logger based on aiologger for my application and I can't use it with uvicorn without changing  code in modules. 
So I can see if FastAPI is started to serve, but I don't see in logs if uvicorn workers started successfully and it bounded to right host and port.

**Comment by lovelydinosaur** [comment]
We're using logger instances in the way Python's stdlib intends them to be used.

You can customize the configuration for those instances using the `log_config` argument, which gives you extensive control over how they should format their logging, which log levels to use, and where output should be directed.

We won't be supporting passing in a logger instance directly, since it runs against the grain of how Python's logging module is intended to be used.
