### ISSUE TITLE
Uvicorn ignores --uds for --reload

### ISSUE THREAD

**Issue by Roang-zero1** [Kludex/uvicorn#586]
As talked about in #368 the `--reload` setting ignores the `--uds` setting, thereby reload binds itself to the default localhost:8000.

In our dev deployment we try to stay as close to production as possible. Due to this issue we have to workaround our nginx config to fall back to a https socket in dev,

I would like to request this feature to be added.

**Comment by lovelydinosaur** [comment]
Personally I'm going to treat this as out of scope at the moment. If someone wants to take a go at a PR for it, I'd happily review it, but otherwise there's no realistic chance of me being able to make time for it.

For now `--reload` is a development setting that shouldn't be used alongside `--uds` which is for use with in production.

Professional Tier Sponsors are able to request priority support... https://github.com/sponsors/encode
