### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'send'

### ISSUE THREAD

**Issue by alairock** [Kludex/uvicorn#607]
I get this error when using the latest uvicorn and starlette in Python 3.8.2

`TypeError: __call__() missing 1 required positional argument: 'send'`

Steps to recreate: 
- clone repo https://github.com/alairock/broke-starlette-uvicorn
- poetry install (make sure you are using Python 3.8)
- `$ poetry run uvicorn src.core:init`
- go to http://localhost:8000/

I can fix it by manually by updating uvicorn>middleware>asgi2.py:L7

```diff
- await instance(receive, send)
+ await instance(scope, receive, send)
```

OR 

I don't know if this is the proper solution, or if there is something else going on, which is why I am reporting an issue and not a merge request.

**Comment by alairock** [comment]
I realize the problem now. `init` is not an instance of starlette but a function that returns it. 

Maybe the solution is to provide a better error message and/or provide validation on the "app" that uvicorn runs.

**Comment by florimondmanca** [comment]
Yes, when the `app` is a string it should point to a fully-defined ASGI callable. In your repro repo the fix would be to call the application factory from within `main()`, and pass the app itself (instead of the string path):

```python
def main():
    app = init()
    uvicorn.run(app, host='0.0.0.0', port=PORT)
```

I think we'd be happy to review any PRs to improve how ASGI apps are validated, but going to close this for now. :-)
