### ISSUE TITLE
Add `reload_pre_restart` & `reload_post_restart` hooks for reacting to server reload

### ISSUE THREAD

**Issue by hanneskuettner** [Kludex/uvicorn#677]
I would love to have an option to programmatically react to a server reload to trigger additional actions (like for example triggering a livereload.com command through a different application).

I think having a pre and a post restart hook would be a nice option.

**Comment by rajasimon** [comment]
I was looking for a way to run typescript when the file changes. 

```
app = Starlette(
    debug=True,
    routes=routes,
    on_startup=[models.database_connect],
    on_shutdown=[models.database_disconnect],
    on_reload=[func_reload]
)

```

Does anyone have idea how to do this? Or alternative.

**Comment by lovelydinosaur** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/). We probably don't realistically have the capacity to add or review any API around that suggestion at the moment, so if you *really* need it you might need to look into other ways around to deal with the reloading workflow.

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)
