### ISSUE TITLE
Running uvicorn as systemd service

### ISSUE THREAD

**Issue by Kinzowa** [Kludex/uvicorn#678]
Hello,

I would like to start `uvicorn` at startup with `systemd` services but for some reason the process exits with an error `status=1/FAILURE`. This is how my service file looks like:

```
Description=Uvicorn systemd service.
After=network.target
StartLimitIntervalSec=0

[Service]
Type=notify
ExecStart=/home/username/env/bin/uvicorn myproject.asgi:application --port 8000 --host 11.202.96.136
User=username
Group=username
RuntimeDirectory=/var/run/uvicorn
WorkingDirectory=/var/www/myproject
ExecReload=/bin/kill -s HUP $MAINPID
KillMode=mixed
TimeoutStopSec=5
PrivateTmp=true
RestartSec=1
Restart=always

[Install]
WantedBy=multi-user.target
```

and the status:

```
root@ubuntu-2cpu-4gb-de-fra1:/lib/systemd/system# systemctl status uvicorn.service
● uvicorn.service - Uvicorn systemd service.
   Loaded: loaded (/lib/systemd/system/uvicorn.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-05-19 10:18:25 UTC; 326ms ago
  Process: 847 ExecStart=/home/username/env/bin/uvicorn myproject.asgi:application --port 8000 --host 11.202.96.136 (code=exited, status=1/FAILURE)
 Main PID: 847 (code=exited, status=1/FAILURE)

May 19 10:18:25 ubuntu-2cpu-4gb-de-fra1 systemd[1]: Failed to start Uvicorn systemd service..

```

What could be the reason behind this error? do you think using `supervisor` is a better option?

Thank you

**Comment by lullis** [comment]
Try changing `Type=notify` to `Type=simple` . I don't believe that uvicorn sends any kind of signal on startup to indicate it's running, and this leads to systemd marking the process as failed to start.

**Comment by lovelydinosaur** [comment]
Hiya. You might have more luck with questions in the chat space... https://gitter.im/encode/community
We're trying to avoid using GitHub for usage questions and discussions, since it simply introduces too much maintainer burden.

**Comment by Asday** [comment]
Respectfully I dislike the suggestion to use some chat program instead of issues.  I'm here two years later wading through this process myself and there's nary a mention of systemd in the official docs, nor is the chat program anywhere near useful for this, given it has no search function and is for chatting.

The example given by the good Kinzowa, along with the fix suggested by the good lullis, however, are at the end of a very simple google search.

**Comment by Kludex** [comment]
I think there's space to improve the `Deployment` section on our docs.

**Comment by Asday** [comment]
Should anyone else turn up here clueless like me, I ended up with the following, where "jingus" is the ficticious name of my project.

`/srv/jingus.example.com/conf/jingus.service`

```
[Unit]
Description=Jingus
After=network.target
Requires=postgresql.service

[Service]
Type=simple
User=jingus
Group=jingus
DynamicUser=true

WorkingDirectory=/srv/jingus.example.com/src/src/jingus
PrivateTmp=true

EnvironmentFile=/srv/jingus.example.com/secrets/env

ExecStart=/srv/jingus.example.com/src/env/bin/uvicorn \
        --proxy-headers \
        --forwarded-allow-ips='*' \
        --workers=4 \
        --port=54748 \
        --no-access-log \
        _.asgi:application
ExecReload=/bin/kill -HUP ${MAINPID}
RestartSec=1
Restart=always

[Install]
WantedBy=multi-user.target
```

* My project is a Django project with the main module named `_`, hence `_.asgi:application`;
* access logging is disabled as my reverse proxy does that elsewhere;
* four workers was a number I pulled out of thin air
* the port I chose [with this link](https://www.random.org/integers/?num=1&min=1025&max=65536&format=plain&col=1&base=10);
* the reason I'm not using a unix socket is because for some reason uvicorn won't do multiple workers unless it's on an INET socket, and setting up something like supervisor or HAProxy for my simple project seemed ridiculous (though if the "some reason" is the stampeding herd, multiple unix sockets with HAProxy is the best way to go);
* using `$RUNTIME_DIRECTORY` in the unit file never seemed to work so I just wrote everything as an absolute path;
* `<...>/src/env/` is a vanilla python virtualenv - heck to poetry, pipenv, and all other such nonsense;
* `<...>/secrets/env` is a poorly named environment variables file suitable for use with systemd, with `0600` permissions - to use its values for management, try `env $(sudo cat ../secrets/env) your_script_that_needs_them`;
* my project happens to use postgresql as a backing database, and my server happens to be running it under systemd, hence the entry under `[Unit]` - of course the correct thing to do is to have the project load and serve a "gimme a moment" page while it waits for the database but that's not what I did;
* there is PLENTY more to do with regards to sandboxing the process such that it can't mess with anything it shouldn't, but again, I've not done that.

From there I ran `sudo systemctl enable /srv/jingus.example.com/conf/jingus.service`

**Comment by jadounrahul** [comment]
in ubuntu its working with rrd rest 
[Unit]
Description=rrdrest
After=network.target

[Service]
Type=simple
User=root
Group=root
DynamicUser=true

WorkingDirectory=/root/rrdrest/RRDReST
PrivateTmp=true

#EnvironmentFile=/usr/local/lib/python3.8/dist-packages/uvicorn

ExecStart=/usr/local/bin/uvicorn rrdrest:rrd_rest --host 0.0.0.0 --port 9000
ExecReload=/bin/kill -HUP ${MAINPID}
RestartSec=1
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by Asday** [comment]
```
User=root
Group=root
DynamicUser=true
```

I'm no systemd expert, but that's either doing something you're not expecting it to do (not running as `root`), or it's doing something you shouldn't do (running as `root`).

I'd recommend keeping `DynamicUser`, and renaming the user and group to something unique to your project.

I'd also get rid of `WorkingDirectory=/root/rrdrest/RRDReST`.  Put it in `/srv/`.  (Or /var/www/ if you're on an older OS and want to for some reason).

**Comment by jadounrahul** [comment]
Thanks @Asday for very good suggestions you are right !
