### ISSUE TITLE
Disable Server Header

### ISSUE THREAD

**Issue by tc8** [Kludex/uvicorn#688]
Hi, 

I'm looking for a  way to prevent the `server:uvicorn` header from being returned in every response. 
I found https://github.com/encode/uvicorn/issues/243 which is similar but the solution doesn't address this particular problem. 

@davidism [asked this question](https://github.com/encode/uvicorn/pull/321#issuecomment-471183072) but @Jitsusama's suggestion of using "middleware to remove it at the last possible second" doesn't work because the default header is added after all the middlewares & routers have run. 

@antirais's [suggestion](https://github.com/encode/uvicorn/issues/243#issuecomment-470603894) of monkey-patching does work but it's very hacky and I'm looking for a cleaner solution.

Thank you

**Comment by lovelydinosaur** [comment]
Hi there, thanks for getting involved. 😃

I'm closing this off for now, since we're moving to a "maintainer driven" policy on our issue tracker & pull request spaces. This will gradually help us ensure that these spaces do a good job of properly reflecting the ongoing project priorities.

The best places to start with this are instead [the chat room](https://gitter.im/encode/community), or [the discussion group](https://discuss.encode.io/).

Many thanks. 💛✨

[Read more about our contribution guidelines.](https://github.com/encode/.github/blob/master/CONTRIBUTING.md)

**Comment by philpraxis** [comment]
To save time to people looking for fast solution (and stumbling on this page):

```
uvicorn my_app:app --no-server-header
```

```

if __name__ == '__main__':
    uvicorn.run('my_app:app', server_header=False)


```

As outlined here:

https://stackoverflow.com/questions/65263792/replace-server-name-with-fake-server-name-in-response-header-in-fastapi

**Comment by euri10** [comment]
it's also in the docs :)
https://www.uvicorn.org/settings/#http

**Comment by alejandro-omni** [comment]
There is an update, the version 0.110.1 not works, to perform the if sentence, and i try different ways but persist the response of server. i used gunicorn to up the server this does not allow header`--header server:firstproject`, it didn't work.

**Update**, finally i found for some one that need ti.

```
from uvicorn.workers import UvicornWorker


class MyUvicornWorker(UvicornWorker):

    def __init__(self, *args, **kwargs):
        self.CONFIG_KWARGS["server_header"] = False
        super().__init__(*args, **kwargs)
```

Run the server 

```
run-program gunicorn main:app  -k uvicorn_worker.MyUvicornWorker
```

https://github.com/sgargel/gunicorn-uvicorn-server-header/blob/main/app/main.py
