### ISSUE TITLE
Fast API Uvicorn worker running 1/2 as fast under Gunicorn.

### ISSUE THREAD

**Issue by drisspg** [Kludex/uvicorn#763]
### Checklist

- [x] I searched the [Uvicorn documentation](https://www.uvicorn.org/) but couldn't find what I'm looking for.
- [x] I looked through similar issues on GitHub, but didn't find anything.
- [x] I looked up "How to do ... in Uvicorn" on a search engine and didn't find any information.
- [x] I asked the [community chat](https://gitter.im/encode/community) for help.

### Question

Hello All. I am running a FastAPI app whose goal is to serve a mxnet model.  While running my fastAPI server using uvicorn with 6 workers a call to the /predict endpoint takes on average 1.57 seconds. If I then switch to running the same app with gunicorn as the process manager with the configuration below. The inference speed approximately doubles to 
3.6 - 4 seconds.  Obviously I would like to run my fastAPI ASGI app using gunicorn to monitor the uvicorn workers.  Any help as to why it would be so much slower running under gunicorn would amazing!

```
{"loglevel": "info", "workers": "6", "bind": "0.0.0.0:8000", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "max_workers": "6", "worker_class": "uvicorn.workers.UvicornWorker", "host": "0.0.0.0", "port": "8000"}
```

**Comment by florimondmanca** [comment]
Hello!

There's no clear reason that would pop to my mind right now — perhaps a mix of Gunicorn doing a bunch of extra things resulting in higher consumption of resources, plus what the `UvicornH11Worker` glue code does might not be optimal or introduce some extra but necessary work?

If you're able to dive into this based on these pointers then please feel free to reach out back with findings. You can also try and ask in the chat about this, see if folks have some other ideas where this might come from. I'd also suggest looking at whether this reproduces for some other frameworks, both sync and non-sync, such as a Flask dev server vs Flask on Gunicorn? Could give you some more hints there…

Anyway, going to close this off for now for housekeeping purposes since it's not clear yet what actionable steps we could take on the Uvicorn side to improve this situation. Thanks!
