### ISSUE TITLE
Uvicorn Asyncio Issue

### ISSUE THREAD

**Issue by AntmanTmp** [Kludex/uvicorn#786]
I know uvicorn use python builtin asyncio and asyncio use select to do event process.
When I use ab to do test in windows env, the concurrency level is 1000, but select throw error

```
ab -n 10000 -c 1000 http://127.0.0.1:8001/
```

error:
```
ValueError: too many file descriptors in select()

Process finished with exit code 1

```
so, what`s the concurrency limitation of uvicorn ?

**Comment by euri10** [comment]
there is an issue template available, please use it

**Comment by cdeler** [comment]
Unfortunately it's not a `uvicorn` limit.

As you can see from stacktrace, `asyncio` uses selectors module to serve connections. The [selectors.DefaultSelector](https://docs.python.org/3/library/selectors.html#selectors.DefaultSelector) in Windows is `select`-based selector.

Talking about `select` limitation in Windows, we can find that python on Windows has `FD_SETSIZE` [512](https://github.com/python/cpython/blob/d051801052211b533c46a593b1c1bccf649a171c/Modules/selectmodule.c#L29) ([msdn select reference](https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select)), so that you cannot handle more than 512 parallel connections in Windows (well, you probably can do that inside WSL but I'm not sure) using Python's `select`.

You can either recompile python with `#define FD_SETSIZE 2000` or try to check it on another platform.

**Comment by florimondmanca** [comment]
Hi @ZosionLee 

I'm closing this issue since it's hard to see what actionable investigation we could do from this. How often does the issue arise, in what conditions, does it reproduce locally, what is the `ab` tool doing exactly, etc… As @euri10 said, this repo provides an issue template that in almost 100% of the times results in higher quality issues, meaning more chances that an issue gets resolved. If you feel like it, please reopen an issue with more details following hints in the template.

Thanks!

**Comment by AntmanTmp** [comment]
Thanks. In addition, frameworks like Tornado have implemented the asynchronous mode early on, while Unicorn uses the asyncio library that comes with python to implement the asynchronous mode. The select module of this library is limited by the platform, and the internal implementation modes of different platforms are different.

**Comment by Tasssadar** [comment]
Hello, I've also encountered this, and it makes uvicorn pretty much unuseable on Windows, because it simply crashes if too many requests are in flight.

I've found https://github.com/encode/uvicorn/issues/529 , but other than reload (which I don't need when it is deployed), I don't see any issues mentioned with the Proactor loop. Would you accept a PR to make it an option again?
