### ISSUE TITLE
Sending SIGTERM to parent process when running with --workers hangs indefinitely

### ISSUE THREAD

**Issue by euri10** [Kludex/uvicorn#852]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When running uvicorn with multiple workers, sending a SIGTERM ie `kill -15 ppid` there's no graceful shutdown and the process hangs indefinitely on https://github.com/encode/uvicorn/blob/ff4af12d6902bc9d535fe2a948d1df3ffa02b0d3/uvicorn/supervisors/multiprocess.py#L57

### Expected behavior

A graceful shutdown

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
`Running uvicorn 0.12.2 with CPython 3.8.6 on Linux`
- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.

### Additional context

originally discovered in https://github.com/encode/uvicorn/issues/364 and mistakenly taken for a docker issue, it's in fact a SIGTERM issue afaiu

**Comment by gnat** [comment]
Ugh deja vu from last year. Child processes no longer getting signals, and not exiting cleanly.

It's unfortunate your additions were reverted.

Can confirm this bug as re-introduced (and hanging linux container deployments such as docker).

**Comment by euri10** [comment]
yep we got a problem with SIGTERM, and not just in docker: it was discovered 1st as a docker issue because it's the default signal sent to exit a container , but the issue exists without containers, so the digging performed in #364 that ended up in a potential fix in #620 was not the right move.

I think #853 is the correct way to handle multi process exits cleanly, it is just too big to review, cant find a way not time to slice it properly

**Comment by Asday** [comment]
Commenting for notifications - I'd really like to see #853's work accepted 'n' merged.

(But am too stupid to help of course).

**Comment by sgsabbage** [comment]
I've been hit by this problem recently and one thing I noticed is that in the `--reload` state specifically, the restart happens fine, but the shutdown does not.

Looking at the code I can see that `restart()` calls `self.process.terminate()` before `self.process.join()`:
https://github.com/encode/uvicorn/blob/87da6cf4082cd28306bdb78d7d42552d131cc179/uvicorn/supervisors/basereload.py#L69-L70

 but `shutdown()` does not:
https://github.com/encode/uvicorn/blob/87da6cf4082cd28306bdb78d7d42552d131cc179/uvicorn/supervisors/basereload.py#L77-L78

In the multiprocess module, `shutdown()` doesn't call `process.terminate()` either:

https://github.com/encode/uvicorn/blob/87da6cf4082cd28306bdb78d7d42552d131cc179/uvicorn/supervisors/multiprocess.py#L65-L67

As far as I can tell, without first calling `terminate()`, `join()` will hang because all `join()` does is wait for the process to terminate, but nothing has told it to. My multiprocessing knowledge is really rusty however, so I'm prepared for all of this to be wrong!

**Comment by Asday** [comment]
@sgsabbage Seems easy enough to test your theory right?  Spin up a docker environment and see if it hangs on termination, then make your change and try again.  If it fixes it and tests still pass, toss up a PR and we might just be away.

**Comment by sgsabbage** [comment]
@Asday Yup, tested it locally and tests still pass. Happy to submit a PR for it if wanted, it could definitely do with a couple more eyes on it.

**Comment by Asday** [comment]
@sgsabbage Please!  I'm in this thread because I was bothered with this behaviour and wanted to know when it got fixed - if your PR is smaller and easier to test 'n' accept than the other one, while still fixing the issue, that sounds great to me.

**Comment by euri10** [comment]
Having spent an awful lot of time exploring various options for this I'm pretty sure calling just terminate () is not the correct way to address the graceful part in "graceful shutdown", but still happy to review a PR that proves me wrong 😁

**Comment by Asday** [comment]
It mightn't prove you wrong, but it might be approaching a solution, in that it's no longer _completely_ broken.  Who knows.  :)

**Comment by sgsabbage** [comment]
As far as I can tell, calling `terminate()` just sends a SIGTERM to each of the child processes, which then handle it appropriately.  As it stands the parent process eats the SIGTERM and so the children never see it and don't know to terminate.

PR inbound!
