### ISSUE TITLE
Ignore changes to any top-level directory starting with a "."

### ISSUE THREAD

**Issue by orf** [Kludex/uvicorn#966]
### Checklist

- [x] There are no similar issues or pull requests for this yet.
- [ ] I discussed this idea on the [community chat](https://gitter.im/encode/community) and feedback is positive.

### Is your feature related to a problem? Please describe.

I want to build a service that accepts file uploads. During development these uploads are saved in a project-level directory. Currently every upload will trigger `uvicorn` to reload:

```
INFO:     127.0.0.1:55846 - "POST /api/v1/upload HTTP/1.1" 200 OK
WARNING:  WatchGodReload detected file change in '['PROJECT_PATH/.media/3fa85f64-5717-4562-b3fc-2c963f66afa6/cropped.png']'. Reloading...
```

## Describe the solution you would like.

The watchgodreload watcher should implement `should_watch_directory` and [apply the same logic as here](https://github.com/encode/uvicorn/blob/master/uvicorn/supervisors/watchgodreload.py#L24).

**Comment by euri10** [comment]
there is an old PR that aims at making this more configurable, will try to find it when time permits

**Comment by orf** [comment]
Making it more configurable would help, but I think ignoring directories starting with a `.` would be a sensible default to have? I personally can't think of any use cases where it would be needed.

**Comment by euri10** [comment]
watchgod by default ignores those directories  `ignored_dirs = {'.git', '__pycache__', 'site-packages', '.idea', 'node_modules'}`

I'd rather have a switch to exclude globs like in https://github.com/encode/uvicorn/pull/820 than a hardcoded one because one day someone will ask it to be removed, revive the PR shouldn't be hard,

another option in current state is for you to specify reload_dirs making sure your `.media` folder is not in it
